fix: change fucking Akim rerender
Akimakimakim00/reactAkim pull request #1
Opened 2022-08-08 14:44 UTC by Byeraon

2022-08-08 14:58 UTC, Byeraon commented
Я в тебя верю, кнопочка тут, чуть-чуть повыше

2022-08-08 15:03 UTC, merged

2022-08-09 12:34 UTC, Akimakimakim00 requested changes

2022-08-09 12:34 UTC, Akimakimakim00 commented on src/components/redux/state.js
> +import { rerenderEntireTree } from "../../render";
все хйня давай поныоой

2022-08-09 12:34 UTC, Akimakimakim00 commented on src/components/redux/state.js
> -  //rerenderEntireTree(state);
хуйян